import { Rubik } from "next/font/google";
import "./globals.css";
import 'swiper/css';
import 'react-vertical-timeline-component/style.min.css';
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { Providers } from "@/providers";
const rubik = Rubik({
  weight: ["300", "400", "500", "600", "700"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} antialiased`}
      >
        <Providers>
        <Header />
        <main className="min-h-[calc(100vh-292px)]">
            {children}
        </main>
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
